Feat/ip radio
docaxess/webcomponents pull request #15
Opened 2024-07-08 11:57 UTC by MarioIpedis

-add test
-add initial state
-add documentation

2024-07-09 06:06 UTC, patrickIpedis requested changes

2024-07-09 06:06 UTC, patrickIpedis commented on packages/radio/src/components/ip-radio/ip-radio.spec.ts
> +  it('passes accessibility standards', async () => {
which accessibility standards ?
It's better to specify the specific accessibility standard we expect instead of a generic one. 
You can split this test and combine what can be put together. 
I think having a more granular test (several more test that test specific behaviour) is better than having a generic one.

2024-07-10 05:23 UTC, yanis-git commented
@MarioIpedis you get un Expected file on your mr.

Cant be merged.

2024-07-10 07:36 UTC, patrickIpedis requested changes

2024-07-10 07:36 UTC, patrickIpedis commented on packages/radio/src/components/ip-radio/ip-radio.tsx
> +              disabled={option.disabled}
https://design.ipedis.com/5dda74a23/p/98cd0a-radio-button/b/81627b

2024-07-10 07:40 UTC, patrickIpedis requested changes

2024-07-10 07:40 UTC, patrickIpedis commented on packages/radio/src/components/ip-radio/ip-radio.tsx
> +        <div class={containerClasses}>
Radio buttons must be placed within a `<fieldset>` which contains a descriptive and meaningful label provided by a the <legend> element to help us organize and clarify the purpose of the radio buttons

2024-07-16 07:18 UTC, yanis-git commented
I close the MR as you get unexpected file on your mr.

Cant be merged. You must ignore Angular folder.. And clean up your git history

2024-07-16 07:18 UTC, closed without merging