Ip table
docaxess/webcomponents pull request #16
Opened 2024-07-09 11:26 UTC by MarioIpedis

2024-07-16 07:24 UTC, yanis-git requested changes

2024-07-16 07:24 UTC, yanis-git commented on packages/table/src/components/table/table.tsx
> +                        d={`M13.9618 5.80875C13.924 5.71738 13.8599 5.63928 13.7777 5.58432C13.6955 5.52936 13.5988 5.50002 13.4999 5.5H3.49991C3.40096 5.49992 3.30421 5.5292 3.22191 5.58414C3.13962
please create a new task to remember this as to be dynamic

2024-07-16 07:24 UTC, yanis-git commented on packages/table/src/README.md
> +    ]'
you can change by single key parameters which will act like 



```
const table = [
  {foo: 'BAR', count: 1},
  {foo: 'test', count: 1},
  {foo: 'dd', count: 1},
];

console.log(Object.keys(table[1]))
```

then you can check consistency across all elements

2024-07-24 07:07 UTC, RomaricMitiana commented on packages/table/src/components/table/table.tsx
> +    }
I think we should throw exception if error occurred instead of log

2024-07-29 06:26 UTC, merged