Feat/accordion
docaxess/webcomponents pull request #26
Opened 2024-07-29 09:01 UTC by MarioIpedis

-accordion component
-test
-readme

2024-07-31 06:55 UTC, RomaricMitiana requested changes
We should find a way to avoid setTimeout() usage.

2024-07-31 06:55 UTC, RomaricMitiana commented on packages/accordion/src/components/accordion/accordion.tsx
> +    }, 0);
ca you explain the reason of the setTimeOut?

2024-07-31 06:55 UTC, RomaricMitiana commented on packages/accordion/src/components/accordion/accordion.tsx
> +      );
shift() method on the array should give the same result

2024-08-01 11:16 UTC, patrickIpedis commented on packages/tab-panel/src/README.md
>  ```
This is confusing so next time better to use a dedicated branch

2024-08-01 11:16 UTC, merged