Feat/modal
docaxess/webcomponents pull request #29
Opened 2024-07-31 13:49 UTC by MarioIpedis

-create modal component
-test
-doc

2024-08-01 11:57 UTC, patrickIpedis requested changes

2024-08-01 11:57 UTC, patrickIpedis commented on packages/modal/src/components/modal/modal.tsx
> +      const lastElement = focusableElements[focusableElements.length - 1];
firstFocusableElement & lastFocusableElement would a be a better name I guess

2024-08-01 11:57 UTC, patrickIpedis commented on packages/modal/src/components/modal/modal.tsx
> +      if (firstFocusableElement) {
try to avoid setTimeOut if possible

2024-08-01 11:57 UTC, patrickIpedis commented on packages/modal/src/components/modal/modal.tsx
> +          aria-haspopup="dialog"
to confirm if we should add an **aria-label** to  the button which opens the modal. Or is it optional
Because here => https://design.ipedis.com/5dda74a23/p/814d58-modal-window/b/81627b 
We don't have such one

2024-08-01 12:15 UTC, patrickIpedis commented on packages/modal/src/components/modal/modal.tsx
> +          aria-haspopup="dialog"
it is confirmed that it is optional

2024-08-01 12:20 UTC, patrickIpedis requested changes

2024-08-01 12:20 UTC, patrickIpedis commented on packages/modal/src/components/modal/modal.tsx
> +            class="close-dialog"
After local test, this behaviour is not functionning properly => 
`Upon the dialog's appearance, focus must automatically be shifted to the first interactive element of the modal window, facilitating seamless navigation for users.`
So after opening the modal (via click, on tab enter on the open dialog button), the focus should be on the close button modal (and it should be visible).

1. Currently, a double focus is needed to close the modal
2. When then modal is closed, it cannot be opened again after pressing on enter

2024-08-05 09:32 UTC, patrickIpedis commented on packages/modal/src/components/modal/modal.tsx
> +    }, 100);
why do we still have a setTimeOut here ?

2024-08-06 13:32 UTC, MarioIpedis commented on packages/modal/src/components/modal/modal.tsx
> +    }, 100);
to wait for the content to load

2024-08-07 05:40 UTC, yanis-git commented on packages/modal/src/components/modal/modal.tsx
> +    }, 100);
But you cant know it will take 100 ms..

A better way is to use

```
requestAnimationFrame(() => { queueMicrotask(() => { ... }); });
```

Which use painting hook and micro task scheduling.

Another way is to use mutation observer

2024-08-07 07:04 UTC, yanis-git requested changes

2024-08-07 07:04 UTC, yanis-git commented on packages/modal/src/components/modal/modal.tsx
> +      }
no need nested if here

```
if (event.shiftKey && document.activeElement === firstFocusableElement) {
  event.preventDefault();
  lastFocusableElement.focus();
}

if (!event.shiftKey && document.activeElement === lastFocusableElement) {
  event.preventDefault();
  this.closeButton.focus();
}
```

2024-08-07 07:04 UTC, yanis-git commented on tsconfig.base.json
> +      "@ipedis/modal/loader": ["dist/libs/modal/loader"],
wrong path

2024-08-08 05:55 UTC, MarioIpedis commented on packages/modal/src/components/modal/modal.spec.ts
> +      </ip-modal>
part is used in conjunction with Shadow DOM to define which elements in a shadow tree can be styled or accessed outside the shadow . This is a way to apply styles to DOM elements while maintaining encapsulation.
I used it to make it as customizable as possible.
For example, to style the button, instead of putting several variables, we can just do like this
ip-modal::part(trigger-button) {
  background-color: #007bff;
  color: white;
  border: none;
  padding: 10px 20px;
  cursor: pointer;
}

2024-08-12 12:19 UTC, yanis-git commented on packages/modal/src/components/modal/modal.tsx
> +      if (firstFocusableElement) {
Je réouvre, un timeout est toujours présent.

2024-08-12 12:43 UTC, MarioIpedis commented on packages/modal/src/components/modal/modal.tsx
> +      if (firstFocusableElement) {
@yanis-git de mon côté il n'y a plus de setTimeOut

2024-08-14 05:54 UTC, yanis-git requested changes

2024-08-14 05:54 UTC, yanis-git commented on tsconfig.base.json
>        "@ipedis/tab-panel": ["dist/packages/tab-panel"],
path

2024-08-14 05:54 UTC, yanis-git commented on packages/show-more/src/components/show-more/show-more.tsx
> +            {this.isExpanded ? (
translatable content

2024-08-14 05:55 UTC, yanis-git commented
Cette MR contiens bien trop de changement non lié, il est préférable de les isoler pour faciliter la relecture

2024-08-14 06:00 UTC, yanis-git requested changes

2024-08-14 06:00 UTC, yanis-git commented on packages/alert/src/components/alert/alert.tsx
> +          tabindex="0"
text not translated.

Why tabindex on button ?

2024-08-14 13:23 UTC, merged