Feat/footnote
docaxess/webcomponents pull request #31
Opened 2024-08-01 05:43 UTC by MarioIpedis

-footnote component
-test 
-readme

2024-08-01 12:05 UTC, patrickIpedis requested changes

2024-08-01 12:05 UTC, patrickIpedis commented on packages/footnote/src/components/footnote/footnote.tsx
> +              height="24"
add aria-hidden=true to the svg

2024-08-07 06:48 UTC, yanis-git requested changes

2024-08-07 06:48 UTC, yanis-git commented on tsconfig.base.json
> +      "@ipedis/footnote/loader": ["dist/libs/footnote/loader"],
wrong path

2024-08-07 06:48 UTC, yanis-git commented on packages/footnote/src/components/footnote/footnote.tsx
> +          <a href={`#ref${this.identifier}`} aria-label="Back to main text">
our main target is french company, we should not have hard coded english text. It should be at list customizable

2024-08-07 06:48 UTC, yanis-git commented on packages/footnote/src/components/footnote/footnote.spec.ts
> +                        <span id="footnote-label-undefined" class="footnote-id">[]</span>
as you can see here, undefined is used as identifier. seams to miss mandatory parameter checking here or a random string as fallback

2024-08-07 06:48 UTC, yanis-git commented on packages/footnote/src/components/footnote/footnote.scss
> +}
you will get css selector collision very easily

2024-08-14 05:49 UTC, yanis-git requested changes

2024-08-14 05:49 UTC, yanis-git commented on packages/footnote/src/components/footnote/footnote.tsx
> +    const id = this.identifier || 'fallback-id';
this fallback will never being applied as you provide a default value for identifier.

Also i have suggested to put random string over static one.

2024-08-14 05:49 UTC, yanis-git commented on packages/show-more/src/components/show-more/show-more.tsx
> +            {this.isExpanded ? 'Show Less' : 'Show More'}
english text which could not be translated

2024-08-14 05:49 UTC, yanis-git commented on tsconfig.base.json
> +      "@ipedis/accordion/loader": ["dist/libs/accordion/loader"],
path

2024-08-14 05:49 UTC, yanis-git commented on tsconfig.base.json
> +      "@ipedis/footnote/loader": ["dist/packages/footnote/loader"],
path

2024-08-14 05:49 UTC, yanis-git commented on tsconfig.base.json
> +      "@ipedis/show-more/loader": ["dist/libs/show-more/loader"],
path

2024-08-14 05:49 UTC, yanis-git commented on packages/show-more/src/components/show-more/show-more.scss
> +}
there is risk of css selector collision here

2024-08-16 05:27 UTC, merged